# Generated by Django 5.0.3 on 2024-05-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreview",
            name="ip",
            field=models.CharField(default=0, max_length=20),
        ),
    ]
